import {p1pipeline, p2pipeline} from "./day06";

const exampleInput = `
....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
`;

test('day6 part1 example works', () => {
    expect(p1pipeline(exampleInput)).toEqual(41)
})

test('day6 part2 example works', () => {
    expect(p2pipeline(exampleInput)).toEqual(6)
})