import {p1pipeline} from "./day08";

const exampleInput = `
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
`;

test('day8 part1 example works', () => {
    expect(p1pipeline(exampleInput)).toEqual(14);
})

test('day8 part2 example works', () => {
})
